//
//    AlbumDetailsPresenterTests.swift
//    NikeSampleiOS
//
//    Created by Andrew Koprowski on 6/30/20.
//    Copyright (c) 2020 Andrew Koprowski. All rights reserved.
//
//    This file was generated by the Clean Swift Xcode Templates so
//    you can apply clean architecture to your iOS and Mac projects,
//    see http://clean-swift.com
//

@testable import NikeSampleiOS
import XCTest

class AlbumDetailsPresenterTests: XCTestCase {
    // MARK: Subject under test

    var sut: AlbumDetailsPresenter!

    // MARK: Test lifecycle

    override func setUp() {
        super.setUp()
        setupAlbumDetailsPresenter()
    }

    override func tearDown() {
        super.tearDown()
    }

    // MARK: Test setup

    func setupAlbumDetailsPresenter() {
        sut = AlbumDetailsPresenter()
    }

    // MARK: Test doubles

    // MARK: Tests
}
