//
//    AlbumDetailsViewControllerTests.swift
//    NikeSampleiOS
//
//    Created by Andrew Koprowski on 6/30/20.
//    Copyright (c) 2020 Andrew Koprowski. All rights reserved.
//
//    This file was generated by the Clean Swift Xcode Templates so
//    you can apply clean architecture to your iOS and Mac projects,
//    see http://clean-swift.com
//

@testable import NikeSampleiOS
import XCTest

class AlbumDetailsViewControllerTests: XCTestCase {
    // MARK: Subject under test

    var sut: AlbumDetailsViewController!
    var window: UIWindow!

    // MARK: Test lifecycle

    override func setUp() {
        super.setUp()
        window = UIWindow()
        setupAlbumDetailsViewController()
    }

    override func tearDown() {
        window = nil
        super.tearDown()
    }

    // MARK: Test setup

    func setupAlbumDetailsViewController() {
        sut = AlbumDetailsViewController()
    }

    func loadView() {
        window.addSubview(sut.view)
        RunLoop.current.run(until: Date())
    }

    // MARK: Test doubles

    class InteractorSpy: AlbumDetailsBusinessLogic {
        var hasFetchAlbumBeenCalled = false
        func fetchAlbum() {
            hasFetchAlbumBeenCalled = true
        }
    }
    // MARK: Tests

    func testViewDidLoadCallsFetchAlbums() {
        // Given
        let interactorSpy = InteractorSpy()
        sut.interactor = interactorSpy
        // When
        sut.viewDidLoad()
        // Then
        XCTAssertTrue(interactorSpy.hasFetchAlbumBeenCalled,
                      "When viewDidLoad is called we should fetchAlbum.")
    }
}
