//
//    ShowAlbumsViewControllerTests.swift
//    NikeSampleiOS
//
//    Created by Andrew Koprowski on 6/28/20.
//    Copyright (c) 2020 Andrew Koprowski. All rights reserved.
//
//    This file was generated by the Clean Swift Xcode Templates so
//    you can apply clean architecture to your iOS and Mac projects,
//    see http://clean-swift.com
//

@testable import NikeSampleiOS
import XCTest

class ShowAlbumsViewControllerTests: XCTestCase {
    // MARK: Subject under test

    var sut: ShowAlbumsViewController!
    var window: UIWindow!

    // MARK: Test lifecycle

    override func setUp() {
        super.setUp()
        window = UIWindow()
        setupShowAlbumsViewController()
    }

    override func tearDown() {
        window = nil
        super.tearDown()
    }

    // MARK: Test setup

    func setupShowAlbumsViewController() {
        sut = ShowAlbumsViewController(style: .plain)
    }

    func loadView() {
        window.addSubview(sut.view)
        RunLoop.current.run(until: Date())
    }

    // MARK: Test doubles

    // MARK: Tests
    func testViewDidLoadSetsTitle() {
        // Given
        loadView()
        let expectedTitle = Constants.showAlbmusVCTitle
        // When
        sut.viewDidLoad()
        // Then
        XCTAssertEqual(expectedTitle, sut.title,
                       "The title of the \(expectedTitle) should be set in viewDidLoad")
    }
}
