//
//    ShowAlbumsWorkerTests.swift
//    NikeSampleiOS
//
//    Created by Andrew Koprowski on 6/28/20.
//    Copyright (c) 2020 Andrew Koprowski. All rights reserved.
//
//    This file was generated by the Clean Swift Xcode Templates so
//    you can apply clean architecture to your iOS and Mac projects,
//    see http://clean-swift.com
//

@testable import NikeSampleiOS
import XCTest

class ShowAlbumsWorkerTests: XCTestCase {
    // MARK: Subject under test

    var sut: ShowAlbumsWorker!

    // MARK: Test lifecycle

    override func setUp() {
        super.setUp()
        setupShowAlbumsWorker()
    }

    override func tearDown() {
        super.tearDown()
    }

    // MARK: Test setup

    func setupShowAlbumsWorker() {
        sut = ShowAlbumsWorker()
    }

    // MARK: Test doubles

    class ApiSpy: ITunesAPIProtocol {
        var hasFetchDataBeenCalled = false
        func fetchData(_ completionHandler: @escaping (Data?, Error?) -> Void) {
            hasFetchDataBeenCalled = true
        }
    }

    // MARK: Tests

    func testFetchFromApiCallsFetchData() {
        // Given
        let apiSpy = ApiSpy()
        sut.api = apiSpy
        // When
        sut.fetchFromAPI { (_) in
            // do nothing
        }
        // Then
        XCTAssertTrue(apiSpy.hasFetchDataBeenCalled,
                      "fetchFromAPI should call fetchData on the api.")
    }

}
