//
//    ShowAlbumsWorker.swift
//    NikeSampleiOS
//
//    Created by Andrew Koprowski on 6/28/20.
//    Copyright (c) 2020 Andrew Koprowski. All rights reserved.
//
//    This file was generated by the Clean Swift Xcode Templates so
//    you can apply clean architecture to your iOS and Mac projects,
//    see http://clean-swift.com
//
import Foundation

/// Definition of worker to get data from API(RSS feed) then return a result which includes Albums
protocol ShowAlbumsWorkerProtocol {
    /// Fetches data from API then converts results into Albums or passes the generated error.
    /// - Parameter completionHandler: Result Enum consisting of an array of Albums on success or Error on failure.
    func fetchFromAPI(_ completionHandler: @escaping (Result<[Album], Error>) -> Void)
}
class ShowAlbumsWorker: ShowAlbumsWorkerProtocol {

    /// Dependency - The api to fetch data from
    var api: ITunesAPIProtocol? = ITunesRSSFeedGenerator()

    func fetchFromAPI(_ completionHandler: @escaping (Result<[Album], Error>) -> Void) {
        api?.fetchData({ (data, error) in
            //
        })
    }
}
