//
//    ShowAlbumsModels.swift
//    NikeSampleiOS
//
//    Created by Andrew Koprowski on 6/28/20.
//    Copyright (c) 2020 Andrew Koprowski. All rights reserved.
//
//    This file was generated by the Clean Swift Xcode Templates so
//    you can apply clean architecture to your iOS and Mac projects,
//    see http://clean-swift.com
//

// swiftlint:disable nesting
enum ShowAlbums {
    // MARK: Use cases

    enum Fetch {
        struct Request {
        }
        struct Response {
            let albums: [Album]
        }
        struct ViewModel {
        }
    }
}

// swiftlint:enable nesting
