//
//    ShowAlbumsRouter.swift
//    NikeSampleiOS
//
//    Created by Andrew Koprowski on 6/28/20.
//    Copyright (c) 2020 Andrew Koprowski. All rights reserved.
//
//    This file was generated by the Clean Swift Xcode Templates so
//    you can apply clean architecture to your iOS and Mac projects,
//    see http://clean-swift.com
//

import UIKit

@objc protocol ShowAlbumsRoutingLogic {
    //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol ShowAlbumsDataPassing {
    var dataStore: ShowAlbumsDataStore? { get }
}

class ShowAlbumsRouter: NSObject, ShowAlbumsRoutingLogic, ShowAlbumsDataPassing {
    weak var viewController: ShowAlbumsViewController?
    var dataStore: ShowAlbumsDataStore?

    // MARK: Routing
}
