//
//    ShowAlbumsModels.swift
//    NikeSampleiOS
//
//    Created by Andrew Koprowski on 6/28/20.
//    Copyright (c) 2020 Andrew Koprowski. All rights reserved.
//
//    This file was generated by the Clean Swift Xcode Templates so
//    you can apply clean architecture to your iOS and Mac projects,
//    see http://clean-swift.com
//
import Foundation

// swiftlint:disable nesting
enum ShowAlbums {

    // MARK: Use cases

    /// Enum to use for the viper loop associated with fetching albums.
    enum Fetch {
        /// The request object used by the view controller to start the viper loop.
        struct Request {
        }
        /// The response used by the presenter to turn domain models into view models.
        struct Response {
            let albums: [Album]
        }
        /// The view model used by the view to display album information.
        struct ViewModel {
            struct Album {
                let name: String
                let artist: String
                var imageData: Data?
            }
            let albums: [Album]
        }
        struct ArtWork {
            let imageData: Data
            let index: Int
        }
    }
}

// swiftlint:enable nesting
