//
//    ShowAlbumsPresenter.swift
//    NikeSampleiOS
//
//    Created by Andrew Koprowski on 6/28/20.
//    Copyright (c) 2020 Andrew Koprowski. All rights reserved.
//
//    This file was generated by the Clean Swift Xcode Templates so
//    you can apply clean architecture to your iOS and Mac projects,
//    see http://clean-swift.com
//

protocol ShowAlbumsPresentationLogic {
    func presentAlbums(response: ShowAlbums.Fetch.Response)
}

class ShowAlbumsPresenter: ShowAlbumsPresentationLogic {
    weak var viewController: ShowAlbumsDisplayLogic?

    // MARK: Fetch albums

    func presentAlbums(response: ShowAlbums.Fetch.Response) {
        let albumViewModels: [ShowAlbums.Fetch.ViewModel.Album] = response.albums.map {
            return ShowAlbums.Fetch.ViewModel.Album(
                name: $0.name ?? Constants.unknownAlbumName,
                artist: $0.artistName ?? Constants.unknownArtistName)
        }
        let viewModel = ShowAlbums.Fetch.ViewModel(albums: albumViewModels)
        viewController?.displayAlbums(viewModel: viewModel)
    }
}
