//
//    ShowAlbumsInteractor.swift
//    NikeSampleiOS
//
//    Created by Andrew Koprowski on 6/28/20.
//    Copyright (c) 2020 Andrew Koprowski. All rights reserved.
//
//    This file was generated by the Clean Swift Xcode Templates so
//    you can apply clean architecture to your iOS and Mac projects,
//    see http://clean-swift.com
//

import UIKit

protocol ShowAlbumsBusinessLogic {
    func doSomething(request: ShowAlbums.Something.Request)
}

protocol ShowAlbumsDataStore {
    //var name: String { get set }
}

class ShowAlbumsInteractor: ShowAlbumsBusinessLogic, ShowAlbumsDataStore {
    var presenter: ShowAlbumsPresentationLogic?
    var worker: ShowAlbumsWorker?

    // MARK: Do something

    func doSomething(request: ShowAlbums.Something.Request) {
        worker = ShowAlbumsWorker()
        worker?.doSomeWork()

        let response = ShowAlbums.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
