//
//    AlbumDetailsPresenter.swift
//    NikeSampleiOS
//
//    Created by Andrew Koprowski on 6/30/20.
//    Copyright (c) 2020 Andrew Koprowski. All rights reserved.
//
//    This file was generated by the Clean Swift Xcode Templates so
//    you can apply clean architecture to your iOS and Mac projects,
//    see http://clean-swift.com
//

import UIKit

protocol AlbumDetailsPresentationLogic {
    func presentAlbum(response: AlbumDetails.Response)
}

class AlbumDetailsPresenter: AlbumDetailsPresentationLogic {
    weak var viewController: AlbumDetailsDisplayLogic?

    // MARK: Fetch Album

    func presentAlbum(response: AlbumDetails.Response) {
        var genreString = ""
        if let genre = response.album.genres {
            let genresArray = genre.filter { $0.name != nil }.map { $0.name }.compactMap { $0 }
            genreString = genresArray.joined(separator: ", ")
        }
        var albumURL: URL?
        if let urlString = response.album.url {
            albumURL = URL(string: urlString)
        }
        let viewModel = AlbumDetails.ViewModel(
            name: response.album.name ?? Constants.unknownAlbumName,
            artist: response.album.artistName ?? Constants.unknownArtistName,
            artwork: response.artworkData,
            genre: genreString,
            releaseDate: response.album.releaseDate ?? "",
            copyright: response.album.copyright ?? "",
            iTunesLink: albumURL)
        viewController?.displayAlbum(viewModel: viewModel)
    }
}
