//
//    AlbumDetailsPresenter.swift
//    NikeSampleiOS
//
//    Created by Andrew Koprowski on 6/30/20.
//    Copyright (c) 2020 Andrew Koprowski. All rights reserved.
//
//    This file was generated by the Clean Swift Xcode Templates so
//    you can apply clean architecture to your iOS and Mac projects,
//    see http://clean-swift.com
//

import UIKit

protocol AlbumDetailsPresentationLogic {
    func presentAlbum(response: AlbumDetails.Response)
}

class AlbumDetailsPresenter: AlbumDetailsPresentationLogic {
    weak var viewController: AlbumDetailsDisplayLogic?

    // MARK: Fetch Album

    func presentAlbum(response: AlbumDetails.Response) {
        // need to implement
    }
}
